repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [push]
      - id: tests
        name: Tests
        entry: make test
        language: system
        pass_filenames: false
        stages: [push]
      - id: docs
        name: Build docs
        entry: make docs
        language: system
        pass_filenames: false
        stages: [push]